name: weather_app_flutter_mvvm
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  dio: ^5.4.3+1
  envied: ^0.5.4+1
  fl_chart: ^0.68.0
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.5
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.0
  flutter_riverpod: ^2.4.1
  freezed: ^2.5.2
  freezed_annotation: ^2.4.1
  gap: ^3.0.1
  hooks_riverpod: ^2.5.1
  intl: ^0.19.0
  json_annotation: ^4.9.0
  riverpod_annotation: ^2.3.5
  riverpod_generator: ^2.3.0
  sticky_headers: ^0.3.0+2
  geolocator: ^12.0.0
  geolocator_android: 4.5.5
  flutter_local_notifications: ^17.1.2

flutter_native_splash:
  image: 'assets/images/splash_logo.png'
  color: '#ffffff'

flutter_icons:
  ios: true
  image_path: 'assets/images/splash_logo.png'
  remove_alpha_ios: true
  android: true

dev_dependencies:
  build_runner: ^2.4.9
  envied_generator: ^0.5.4+1
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
